// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Msg struct {
	MsgId            *uint64 `protobuf:"varint,1,req,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	Ring             *bool   `protobuf:"varint,2,opt,name=ring" json:"ring,omitempty"`
	Vibrate          *bool   `protobuf:"varint,3,opt,name=vibrate" json:"vibrate,omitempty"`
	Cleanable        *bool   `protobuf:"varint,4,opt,name=cleanable" json:"cleanable,omitempty"`
	Trans            *int32  `protobuf:"varint,5,opt,name=trans" json:"trans,omitempty"`
	Begin            *string `protobuf:"bytes,6,opt,name=begin" json:"begin,omitempty"`
	End              *string `protobuf:"bytes,7,opt,name=end" json:"end,omitempty"`
	Title            *string `protobuf:"bytes,8,opt,name=title" json:"title,omitempty"`
	Text             *string `protobuf:"bytes,9,opt,name=text" json:"text,omitempty"`
	Logo             *string `protobuf:"bytes,10,opt,name=logo" json:"logo,omitempty"`
	Url              *string `protobuf:"bytes,11,opt,name=url" json:"url,omitempty"`
	Ctime            *int32  `protobuf:"varint,12,opt,name=ctime" json:"ctime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Msg) GetMsgId() uint64 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *Msg) GetRing() bool {
	if m != nil && m.Ring != nil {
		return *m.Ring
	}
	return false
}

func (m *Msg) GetVibrate() bool {
	if m != nil && m.Vibrate != nil {
		return *m.Vibrate
	}
	return false
}

func (m *Msg) GetCleanable() bool {
	if m != nil && m.Cleanable != nil {
		return *m.Cleanable
	}
	return false
}

func (m *Msg) GetTrans() int32 {
	if m != nil && m.Trans != nil {
		return *m.Trans
	}
	return 0
}

func (m *Msg) GetBegin() string {
	if m != nil && m.Begin != nil {
		return *m.Begin
	}
	return ""
}

func (m *Msg) GetEnd() string {
	if m != nil && m.End != nil {
		return *m.End
	}
	return ""
}

func (m *Msg) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Msg) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *Msg) GetLogo() string {
	if m != nil && m.Logo != nil {
		return *m.Logo
	}
	return ""
}

func (m *Msg) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *Msg) GetCtime() int32 {
	if m != nil && m.Ctime != nil {
		return *m.Ctime
	}
	return 0
}

func init() {
	proto.RegisterType((*Msg)(nil), "protos.Msg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x8e, 0xc1, 0x4e, 0xc4, 0x20,
	0x10, 0x86, 0xb3, 0x6d, 0xe9, 0x2e, 0xa3, 0x07, 0x33, 0xd1, 0x64, 0x0e, 0x1e, 0x36, 0x9e, 0x7a,
	0xf2, 0x3d, 0x3c, 0x78, 0xe1, 0x05, 0x0c, 0x6d, 0x09, 0x21, 0xa1, 0x60, 0x00, 0x8d, 0x0f, 0xe1,
	0x43, 0x0b, 0x43, 0xcc, 0x9e, 0xfa, 0x7f, 0xdf, 0x5f, 0xfe, 0x0c, 0xc8, 0x23, 0xdb, 0xd7, 0xcf,
	0x14, 0x4b, 0xc4, 0x99, 0x3f, 0xf9, 0xe5, 0x77, 0x80, 0xf1, 0x3d, 0x5b, 0x7c, 0x82, 0xb9, 0x96,
	0x1f, 0x6e, 0xa7, 0xd3, 0x75, 0x58, 0x26, 0x25, 0x2a, 0xbd, 0xed, 0x88, 0x30, 0x25, 0x17, 0x2c,
	0x0d, 0xd7, 0xd3, 0x72, 0x51, 0x9c, 0x91, 0xe0, 0xfc, 0xed, 0xd6, 0xa4, 0x8b, 0xa1, 0x91, 0xf5,
	0x3f, 0xe2, 0x33, 0xc8, 0xcd, 0x1b, 0x1d, 0xf4, 0xea, 0x0d, 0x4d, 0xdc, 0xdd, 0x04, 0x3e, 0x82,
	0x28, 0x49, 0x87, 0x4c, 0xa2, 0x36, 0x42, 0x75, 0x68, 0x76, 0x35, 0xd6, 0x05, 0x9a, 0xab, 0x95,
	0xaa, 0x03, 0x3e, 0xc0, 0x68, 0xc2, 0x4e, 0x67, 0x76, 0x2d, 0xf2, 0x6b, 0x57, 0xea, 0xee, 0xa5,
	0xff, 0xc7, 0xd0, 0xee, 0x2b, 0xe6, 0xa7, 0x90, 0x64, 0xc9, 0xb9, 0x39, 0x1f, 0x6d, 0x24, 0xe8,
	0xae, 0xe5, 0xb6, 0xf7, 0x95, 0x3c, 0xdd, 0xf5, 0xbd, 0x1a, 0xdb, 0xde, 0x56, 0xdc, 0x61, 0xe8,
	0xbe, 0x5f, 0xc3, 0xf0, 0x17, 0x00, 0x00, 0xff, 0xff, 0x58, 0xf9, 0x98, 0xe8, 0x22, 0x01, 0x00,
	0x00,
}
